relay:
  address: "localhost:8080"
  # tls:
  #   cert: "./localhost.crt"
  #   key: "./localhost.key"
uplink:
  timeout: 10
  retryCount: 5
  urls:
    - "https://uplink.api.apollographql.com/"
    - "https://aws.uplink.api.apollographql.com/"
cache:
  duration: 60 # Cache duration in seconds
  maxSize: 1024
supergraphs:
  graphRefs:
    "${APOLLO_GRAPH_REF}": "${APOLLO_KEY}"
polling:
  enabled: true
  interval: 10
webhook:
  enabled: true
  path: "/webhook"
  secret: "${APOLLO_WEBHOOK_SECRET}"